apiVersion: v1
kind: Pod
metadata:
  name: pdf-text-token-converter
  namespace: data-prep
spec:
  containers:
  - name: pdf-text-token-converteg
    image: baldbodybuilder/text-token-converter:local
    command: ['sh', '-c', 'echo "Sleeping for 5"; sleep 5; python text-to-tokenid.py --input-dir /data/pdfs/processed --output-dir /data/pdfs/pruned']
    volumeMounts:
      - mountPath: /data/pdfs
        name: pdf-volume
  volumes:
    - name: pdf-volume
      persistentVolumeClaim:
        claimName: pdf-data-pvc
