apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-data-pvc
  namespace: data-prep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: pdf-data-pv
