apiVersion: v1
kind: PersistentVolume
metadata:
  name: checkpoint-pv
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
  claimRef:
    name: checkpoint-pvc
    namespace: data-prep
     
