apiVersion: v1
kind: Pod
metadata:
  name: fine-tuner
  namespace: data-prep
spec:
  containers:
  - name: fine-tuner
    image: baldbodybuilder/fine_tuner:local
    resources:
      requests:
        cpu: "1"
        memory: "8Gi"
        nvidia.com/gpu: 1
      limits: 
        cpu: "2"
        memory: "16Gi"
        nvidia.com/gpu: 1
    volumeMounts:
      - mountPath: /data/pdfs
        name: pdf-volume
    volumes:
      - name: pdf-volume
        persistentVolumeClaim:
          claimName: pdf-data-pvc
