apiVersion: v1
kind: Pod
metadata:
  name: pdf-preprocessor
  namespace: data-prep
spec:
  containers:
  - name: uploader
    image: baldbodybuilder/pdf-preprocessor:v1.3
      #command: ['sh', '-c', 'sleep 3600']
    resources:
      limits:
        cpu: "2"
        memory: "16Gi"
      requests:
        cpu: "1"
        memory: "8Gi"
    volumeMounts:
      - mountPath: /data
        name: pdf-volume
  volumes:
    - name: pdf-volume
      persistentVolumeClaim:
        claimName: pdf-data-pvc
