apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdf-data-pv
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/pdf-data
  claimRef:
    name: pdf-data-pvc
    namespace: data-prep
     
