apiVersion: v1
kind: Pod
metadata:
  name: pdf-uploader
  namespace: data-prep
spec:
  containers:
  - name: uploader
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
      - mountPath: /data
        name: pdf-volume
  volumes:
    - name: pdf-volume
      persistentVolumeClaim:
        claimName: pdf-data-pvc
