apiVersion: batch/v1
kind: Job
metadata:
  name: pdf-preprocessor
  namespace: data-prep
spec:
  parallelism: 4
  completions: 4
  template:
    spec:
      containers:
      - name: pdf-processor
        image: baldbodybuilder/pdf-preprocessor:v1.3
        resources:
          limits:
            cpu: "2"
            memory: "16Gi"
          requests:
            cpu: "1"
            memory: "8Gi"
        volumeMounts:
        - mountPath: /data
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pdf-data-pvc
      restartPolicy: OnFailure
